### ISSUE TITLE
Settings - My Accounts Page

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/Volkswagen-email-corporate-communications-CMS#123]
# Design File
The specs for page can be found in the [Figma design file](https://www.figma.com/file/GONpIBrQ53ukjJhq0Hl9su/Volkswagen-New?node-id=1713%3A22637)

For the design and the flow, go to the "Prototype" page. For the smart suggestion warnings/article prioritization/layout, see "Logic Map" page.

# My Accounts
Your mission, should you accept, includes these tasks: 
--information prefilled
- [x] 1. [Top Navigation ](#top-navigation) 
- [x] 2. [Profile Avator](#text-input)
- [x] 3. [Your Info](#info-form)

![image](https://user-images.githubusercontent.com/5694308/81158300-093a7c80-8fb2-11ea-99eb-34715ad4f068.png)

<h2 id="top-navigation">1. Top Navigation</h2> 

![image](https://user-images.githubusercontent.com/63047208/80683449-68018100-8aee-11ea-80b3-23794954d9e6.png)

##  Content 
Title: My Account
Back: (Leads to Settings )

## Text Style
Title: 
```
/* Mobile H2 */

font-family: Work Sans;
font-style: normal;
font-weight: 600;
font-size: 22px;
line-height: 26px;
```
## Colors 
Top Nav Bar Background: Primary (#FFFFFF, 100%)
Title: On Primary, (#011D51, 100%)

<h2 id="profile-avator">1. Profile Avator</h2> 

![image](https://user-images.githubusercontent.com/63047208/80682797-5cfa2100-8aed-11ea-8da5-5fa8938a0f6c.png)

## Content

User Name: {{ User Name }} 
User Image {{User Image}}

## Text Style
```
/* Mobile H1 */

font-family: Work Sans;
font-style: normal;
font-weight: bold;
font-size: 32px;
line-height: 38px;
display: flex;
align-items: center;
text-align: center;
```
## Color

User Name: On Primary, High Emphasis (FFFFFF, 100%)
Background:
```
/* Blue Gradient Background */

background: radial-gradient(50% 49.2% at 0% 0.8%, rgba(255, 255, 255, 0.25) 0%, rgba(255, 255, 255, 0) 100%), #011D51;
```

<h2 id="Info-Form">2. Your Info </h2> 

![image](https://user-images.githubusercontent.com/5694308/81158239-f9bb3380-8fb1-11ea-9f1b-f9cedaebb41b.png)

## Content
Title 1: Your Info
Text Field 1 Floating Label: Name
Text Field 1 Input: {{ User Name }} 
Text Field 2 Floating Label: Email
Text Field 2 Input: {{ user email }}
Text Field 3 Floating Label: Password
Text Field 3 Input: {{ Should display correct password character count in ● }}
Hyperlink: Reset Password (Leads to reset password flow) 

## Text Style
Title: 
```
/* Mobile H2 */

font-family: Work Sans;
font-style: normal;
font-weight: 600;
font-size: 22px;
line-height: 26px;
```

Text Field Floating Label, Hyperlink: 
```
/* Mobile Caption */

font-family: Work Sans;
font-style: normal;
font-weight: normal;
font-size: 12px;
line-height: 16px;
/* identical to box height, or 133% */
```

Text Field Input, Labels: 
```
/* Mobile Body 1 */

font-family: Work Sans;
font-style: normal;
font-weight: normal;
font-size: 16px;
line-height: 20px;
/* identical to box height, or 125% */
```

## Color
Title: Primary (#011D51)
Text Field Labels: On Background, Medium (#000000, 54%) 
Text Field Border: On Background, Disabled (#000000, 38%) 
Text Field Input: On Background, High (#000000, 84%) 
Hyperlink: Secondary Color (#03B3F9)

**Comment by paulchrisluke** [comment]
![image](https://user-images.githubusercontent.com/5694308/81462553-8a298c00-91dd-11ea-9675-5137f00cfec7.png)
These fields should be prefilled, @atharva3010 i think with information from the api?

**Comment by paulchrisluke** [comment]
Reset Password needs to be connected to the password reset flow 
https://github.com/whynotearth/Volkswagen-email-corporate-communications-CMS/issues/134

**Comment by paulchrisluke** [comment]
# Text Input 
![gif](https://i.gyazo.com/535727fc6fd259037876e6a52c61dcde.gif)
Text disappears as soon as you click away. 

What we want is for the text to stay because the information is being saved. @atharva3010 please confirm that the information is actually being saved

# Reset Password Button
![gif](https://i.gyazo.com/965084864f5dcba07af1ac5bd435432a.gif)
This button is not connected. hyperlink "reset password" button to /views/ResetPassword
Anytime someone presses this button, regardless of input text, it should lead to the reset password page

**Comment by chris-saburo** [comment]
Done it.

**Comment by paulchrisluke** [comment]
@ctyar do we have endpoints to allow them to edit their name/email? We will also need GET endpoints, to display the name/email through the app

**Comment by ctyar** [comment]
The name and email endpoints:
GET `/api/v0/profile`
PUT `/api/v0/profile`

**Comment by chris-saburo** [comment]
ok, let me try to fix it out.

**Comment by mort3za** [comment]
> ok, let me try to fix it out.

because you're working on this, moved to in progress. @chris-saburo

**Comment by paulchrisluke** [comment]
![My Account](https://user-images.githubusercontent.com/5694308/82051973-0e4fa800-96e5-11ea-8fed-10f1ff9d38df.png)
@atharva3010 @chris-saburo updated design with better ux
