### ISSUE TITLE
Bottom Navigation Animation

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/Volkswagen-email-corporate-communications-CMS#141]
# Design File
The specs for page can be found in the [Figma design file](https://www.figma.com/file/GONpIBrQ53ukjJhq0Hl9su/Volkswagen-New?node-id=1713%3A22637)

This issue is for adding animation into the bottom navigation of staging.thebluedelta.com

# Bottom Navigation Fab button 
We want the + icon to animate by rotating 90 degrees to x, and have the related actions appear from bottom to top 

You can see an example of it here: 
![gif](https://i.gyazo.com/a055c3d637593b7f565b57435a226780.gif)
https://material.io/components/buttons-floating-action-button#types-of-transitions

# Bottom Navigation buttons
There should be an animated color transition between active and inactive bottom navigation
![gif](https://i.gyazo.com/9416c676cf5e83f7690a4a09cd983d31.gif)
https://material.io/components/bottom-navigation#behavior

# Page Refresh Navigation 
Right now, when you navigate to a different page, everything on the page reloads, including the botton navigation 
Keep bottom nav static instead of reloading with the page as you are navigating in between pages, just like shown here: 
![gif](https://i.gyazo.com/8b507a6f4dc93a39fb1aef62792c6913.gif)
https://material.io/components/bottom-navigation#behavior

# the bottom nav should also dissapear on scroll, as described in material design.

**Comment by chris-saburo** [comment]
https://github.com/whynotearth/Volkswagen-email-corporate-communications-CMS/pull/183

**Comment by paulchrisluke** [comment]
@chris-saburo the mouse curser should switch to a pointer when hovering over the fab button:

![image](https://user-images.githubusercontent.com/5694308/81247833-3126f000-9045-11ea-92fe-79f2323cc8c0.png)


like this:

![image](https://user-images.githubusercontent.com/5694308/81247869-44d25680-9045-11ea-85f8-11697fa76728.png)
