### ISSUE TITLE
Error message placement in forms

### ISSUE THREAD

**Issue by mort3za** [whynotearth/Volkswagen-email-corporate-communications-CMS#147]
https://github.com/whynotearth/Volkswagen-email-corperate-communications/issues/17#issuecomment-622724935

Check all forms, including memo and post creation.

![image](https://user-images.githubusercontent.com/510242/80908616-8c4f9e80-8d36-11ea-805a-c1cf88897521.png)

**Comment by paulchrisluke** [comment]
closing as duplicate of #38

**Comment by paulchrisluke** [comment]
Wait this is for memos heh. re-opening
