### ISSUE TITLE
connect blue delta stats page to api

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/Volkswagen-email-corporate-communications-CMS#150]
# Design File
The specs for page can be found in the [Figma design file](https://www.figma.com/file/GONpIBrQ53ukjJhq0Hl9su/Volkswagen-New?node-id=1713%3A22637)

For the design and the flow, go to the "Prototype" page. This issue is for the blue delta stats page/open rate page  

The components have already been created. The flow is identical to these issues: 
https://github.com/whynotearth/Volkswagen-email-corperate-communications/issues/76
https://github.com/whynotearth/Volkswagen-email-corperate-communications/issues/77
https://github.com/whynotearth/Volkswagen-email-corporate-communications-CMS/issues/82

# Blue Delta Stats Component / Stats page
![image](https://user-images.githubusercontent.com/5694308/80913210-16b2f500-8d6d-11ea-8b30-7d16d9e6ad39.png)
![image](https://user-images.githubusercontent.com/5694308/80913045-8922d580-8d6b-11ea-83b5-6077d6a8e885.png)
This section is a list of these components, and each component is a memo sent out. On tap, one of these components will open the memo's "open rate #77 " page, so they can view subscribers (unread and opened)

This component has minor edits compared to the original memo stats component 

## Content 
**Title:** {{ Blue Delta Publish Date }}  
**Email Excerpt**: {{bullet list of email's posts, until exceeds content area, then use "..." }} 
**Image**: {{ Email Preview }} 
**Distribution List Chips**: {{ Distribution List }} (this is the identical chip as the memo "To: " field, without the "x" icon https://github.com/whynotearth/Volkswagen-email-corperate-communications/issues/62)
**Stats Title:** Open rate: {{open rate}} {{ x users opened / total users }}
**Stats Bar:** {{ Display open rate in blue progress bar }} 

## Text Style
Title:
```
/* Body 1 Emphasis */

font-family: Work Sans;
font-style: normal;
font-weight: 600;
font-size: 16px;
line-height: 20px;
/* identical to box height, or 125% */
```

Excerpt, Open rate: 
```
/* Caption */

font-family: Work Sans;
font-style: normal;
font-weight: normal;
font-size: 12px;
line-height: 16px;
/* identical to box height, or 133% */
```

## Color
Card Background; Surface (#FFFFFF)
Title: On Background High Emphasis (#000000, 84%)
Exerpts: On Background Disabled (#000000, 84%)
Open Rate: On Background High Emphasis (#000000, 84%) 
Open rate fraction: On background Medium Emphasis (#000000, 54%) 
Progress Bar Background: On Background, Divider (#000000, 12%) 
Progress Bar: 
```
/* Light Blue Gradient */

background: linear-gradient(90deg, #0374F9 0%, #03B3F9 100%);
```

**Comment by paulchrisluke** [comment]
https://github.com/whynotearth/Volkswagen-email-corporate-communications-CMS/pull/153

Completed by @abdullahcalisir12 (Thank you!!) in review now.

**Comment by paulchrisluke** [comment]
@chris-saburo , have you started on this? if not I may re-assign it and have you work on some more animation stuff

**Comment by chris-saburo** [comment]
still not

**Comment by chris-saburo** [comment]
I done it. :)

**Comment by paulchrisluke** [comment]
page almost ready, need blue delta / jumpstart stats endpoints, same as memo sending

**Comment by paulchrisluke** [comment]
endpoint for data /api/v0/volkswagen/distributiongroups/stats

**Comment by ctyar** [comment]
For the stats implemented two new endpoints:
GET `/api/v0/volkswagen/jumpstart/stats`
GET `​/api​/v0​/volkswagen​/jumpstart​/{jumpStartId}​/stats`

Also, I reviewed the Figma designs and it seems we changed some of the old pages so I removed this endpoint:
GET `/api/v0/volkswagen/distributiongroups/stats `
In case we are still using this and I missed something please notify me.

Also one minor breaking change in memo stats I renamed a field in the results:
`api/v0/volkswagen/memos/{memoId}/stats`
`MemoList` -> `MemoStat`

**Comment by smebrahimi** [comment]
change other path
api/v0/volkswagen/memos -> api/v0/volkswagen/memos/stats
api/v0/volkswagen/memos/{memoId}/stats MemoList -> MemoStat

**Comment by paulchrisluke** [comment]
@smebrahimi 

can you please link the blue delta stats button here https://deploy-preview-299--eloquent-thompson-534232.netlify.app/stats

to the page you built so we can test? thank you!

**Comment by paulchrisluke** [comment]
@smebrahimi please change the header to say Blue Delta Stats

make the component the same component style we use for the current memo stats (rigth aligned images, no animated bar, etc).

![image](https://user-images.githubusercontent.com/5694308/82774293-9f094f00-9e6e-11ea-935a-22d0bd28ad19.png)

@ctyar I don't understand these stats, I should be seeing the entire dist list members and then unread/read when I click in? 

https://deploy-preview-299--eloquent-thompson-534232.netlify.app/activity-feed/jump-starts/56

**Comment by ctyar** [comment]
@paulchrisluke It should be fixed now

**Comment by bamboochow** [comment]
These Blue Delta Emails displayed in the stats contain future dates. Blue Delta Stats should be showing SENT email statistics only 
![image](https://user-images.githubusercontent.com/14948326/82801836-21623500-9ea8-11ea-88db-68efc8d93b6d.png)

But UI looks good

**Comment by paulchrisluke** [comment]
@ctyar @smebrahimi looks good approved to merge if its passed code review.
