### ISSUE TITLE
Blue Delta Page 

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/Volkswagen-email-corporate-communications-CMS#174]
# Design File
The specs for page can be found in the [Figma design file](https://www.figma.com/file/GONpIBrQ53ukjJhq0Hl9su/Volkswagen-New?node-id=1713%3A22637)

For the design and the flow, go to the "Prototype (mobile)" page. This issue is for the blue delta page

# Blue Delta Page / Component  
This is a new Blue Delta Page That displays the content of each future jumpstart. All created articles should be displayed here by dates, 

![image](https://user-images.githubusercontent.com/5694308/81143147-827aa500-8f9b-11ea-907c-734028d0bfbb.png)

Your mission, should you accept, includes these tasks: 

- [ ] 1. [Top Navigation ](#top-navigation) #25 
- [ ] 2. [Blue Delta Component](#blue-delta-component) 

<h1 id="top-navigation">1. Top Navigation</h1> 

![image](https://user-images.githubusercontent.com/5694308/81141051-9d4a1b00-8f95-11ea-9e9d-e9e309ef9ef5.png)

## Content 
This is the same as all the top navigations (/src/components/BaseAppBarHeader.vue)
Title: Blue Delta 
Back Icon: (Leads to Dashboard)

<h1 id="blue-delta-component">2. Blue Delta Component</h1> 

![image](https://user-images.githubusercontent.com/5694308/81143112-74c51f80-8f9b-11ea-9921-9f21ae654689.png)
This component displays a list of all articles included for that date, separated by dividers 

## Content 
Title: {{ Day of week }}, {{ day }} {{Month}}, {{year}}
List Iem: {{Icon of category}} {{Title of Article}} 

On tap, the blue delta component will open the "Edit Blue Delta" page #179 

## Text Style 
Title:
```
/* Mobile Body 1 Emphasis */

font-family: Work Sans;
font-style: normal;
font-weight: 600;
font-size: 16px;
line-height: 20px;
/* identical to box height, or 125% */
```

List Item: 
```
/* Mobile Caption */

font-family: Work Sans;
font-style: normal;
font-weight: normal;
font-size: 12px;
line-height: 16px;
/* identical to box height, or 133% */
```

## Color 
Title: On Background, High (#000000, 84%) 
List Item: On Background, Medium (#000000, 54%) 
Divider: On Background, Divider (#000000, 12%) 
List Item Icons: {{ Category color }}

**Comment by smebrahimi** [comment]
@paulchrisluke UI finished, I'll bind data after ready from the backend

**Comment by ctyar** [comment]
GET `​/api​/v0​/volkswagen​/articles​/dailyplan`

**Comment by paulchrisluke** [comment]
# Top Navigation 
![image](https://user-images.githubusercontent.com/5694308/81545719-7a5ba480-93a3-11ea-8c64-ad04daa63cda.png)
Top navigation should be sticky to the top of viewing window and should not move when scrolling 

# Bottom Navigation
![image](https://user-images.githubusercontent.com/5694308/81545700-73cd2d00-93a3-11ea-8346-b1912671b736.png)
Bottom navigation needs to be added into the page, same as other pages (was hidden in design to better show page, sorry)

**Comment by smebrahimi** [comment]
![Screenshot from 2020-05-11 19-01-44](https://user-images.githubusercontent.com/8133270/81573588-ea752500-93b9-11ea-9ca4-f8e40b6d8910.png)
