### ISSUE TITLE
Update Dashboard Page 

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/Volkswagen-email-corporate-communications-CMS#175]
# Design File
The specs for page can be found in the [Figma design file](https://www.figma.com/file/GONpIBrQ53ukjJhq0Hl9su/Volkswagen-New?node-id=1713%3A22637)

For the design and the flow, go to the "Prototype" page. This issue is for the blue delta stats page/open rate page  

# Current Dashboard 
![image](https://user-images.githubusercontent.com/5694308/81143369-e9985980-8f9b-11ea-99b4-f229403a2deb.png)
This is our current temporary dashboard design https://thebluedelta.com/

![image](https://user-images.githubusercontent.com/5694308/81143656-8824ba80-8f9c-11ea-8273-317eb4dfbe2e.png)
Our real dashboard design/visual development is done, but is not currently in use 
https://thebluedelta.com/dashboard

# Updated Dashboard 
Switch over from the current temporary dashboard to our actual dashboard designs
![image](https://user-images.githubusercontent.com/5694308/81143728-b7d3c280-8f9c-11ea-9e77-42f3ebcfb10c.png)

Our updated Dashboard design requires these steps: 
- [x] 1. Hide Smart Suggestions Section 
- [x] 2. Add and connect Settings button
- [x] 3. Remove statistics section in user profile 
- [x] 4. Image of email should be replaced with actual email preview for today

**Comment by paulchrisluke** [comment]
hide avatar please, we don't have an endpoint for that @smebrahimi

**Comment by smebrahimi** [comment]
> hide avatar please, we don't have an endpoint for that @smebrahimi

with user name?

**Comment by paulchrisluke** [comment]
![image](https://user-images.githubusercontent.com/5694308/81534494-56439780-9392-11ea-995a-cdc52050b193.png)
We are not using this temporary home/dashboard page anymore. We are replacing this one with our new dashboard page (below). 
![image](https://user-images.githubusercontent.com/5694308/81534548-6c515800-9392-11ea-8b67-386aa2b1e9d8.png)

# Log In 
When you log in, this is the page that needs to be displayed. 
![image](https://user-images.githubusercontent.com/5694308/81534590-7e32fb00-9392-11ea-8b0f-b03f62bbfb91.png)

# Bottom Navigation 
![image](https://user-images.githubusercontent.com/5694308/81534642-986cd900-9392-11ea-90eb-cc09aad65c80.png)
When you click "home", users should be redirected to the new dashboard

# Settings Back Button 
![gif](https://i.gyazo.com/7f1fb6166b090b0bb633dd9fe77cacf7.gif)
When you press "back" from the new dashboard page, it should not go back to the old "welcome to blue delta" home page, it should go to Dashboard
