### ISSUE TITLE
Add text editor to headline and description fields

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/Volkswagen-email-corporate-communications-CMS#176]
We need to pick an editor. I love medium.com's the best. its the cleanest. 

Goal: Xavier needs to be able to write in these modules ina  way that feels familiar to outlook/word. He may also be copying content he wrote in word over to our cms and pasting there. We need to support all that, and show the same output in our blue delta printed and emailed versions.

possible solutions:
https://www.vue2editor.com/

![image](https://user-images.githubusercontent.com/5694308/81143714-b0141e00-8f9c-11ea-9114-6d071bbd7125.png)

**Comment by paulchrisluke** [comment]
nevermind, think we are going to build our own component like a boss.

@atharva3010 

```
Yeah, @mort3za I think it’s better to pull quill.js directly and use it in our own component
Vue2editor seems very bulky
Vue2editor was last updated 9 months ago, we don’t know if it’ll be actively maintained. So it might be better to create our own wrapper component for quill. What do you think?
```

**Comment by mort3za** [comment]
Had a discussion with @atharva3010 for choosing an editor. Quill don't support markdown. So we chose [simplemde](https://simplemde.com/). I see an image button in design, we add post image in image uploader, so we don't need that button.  
For separation of textarea and toolbar, I don't know if it's possible or not with simplemde, Atharva will check it, if that was not possible, should change design to a normal editor.
@paulchrisluke

**Comment by atharva3010** [comment]
Yeah, we cannot separate toolbar and the text area in simplemde. It restricts our styling a bit too, we may need to adjust design accordingly.

**Comment by atharva3010** [comment]
Regarding heading, I think styling should be only for the description field. If we style heading in markdown too, it may break the layout of the components like article/post cards in rearrange.

**Comment by paulchrisluke** [comment]
I agree just description bar is fine. Is this ready to review from a user perspective @atharva3010 ?

**Comment by paulchrisluke** [comment]
@abdullahcalisir12 I think we are ready to merge this (do not include the image upload), if it has been reviewed by @atharva3010 @mort3za ?

**Comment by mort3za** [comment]
@ctyar editor is merged. you can enable markdown to html convertor in backend. I'll send the styles later.

**Comment by ctyar** [comment]
@mort3za Done

**Comment by paulchrisluke** [comment]
@abdullahcalisir12 please add this to the excerpt field as well

**Comment by abdullahcalisir12** [comment]
@paulchrisluke  I added base editor to excerpt field you can check it here #337

**Comment by paulchrisluke** [comment]
@abdullahcalisir12 looks good, approved from ux. pending code review
