### ISSUE TITLE
Stats Page

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/Volkswagen-email-corporate-communications-CMS#178]
# Design File
The specs for page can be found in the [Figma design file](https://www.figma.com/file/GONpIBrQ53ukjJhq0Hl9su/Volkswagen-New?node-id=1713%3A22637)

For the design and the flow, go to the "Prototype" page. This issue is for the blue delta stats page/open rate page  

# Stats Page 
![image](https://user-images.githubusercontent.com/5694308/81144940-5cef9a80-8f9f-11ea-836e-13beb6e1f803.png)
We are reusing our previous temporary dashboard designs for the stats page

Your mission, should you accept, includes these tasks: 

- [x] 1. [Top Navigation ](#top-navigation) 
- [x] 2. [Stats Page](#stats-page) 

<h1 id="top-navigation">1. Top Navigation</h1> 

![image](https://user-images.githubusercontent.com/5694308/81145011-8dcfcf80-8f9f-11ea-839a-91fe7253bc8d.png)

## Content 
This is the same design as all the top navigations (/src/components/BaseAppBarHeader.vue)
Title: Stats
Back Icon: (Leads to Dashboard)

<h1 id="stats-page">2. Stats Page</h1> 

![image](https://user-images.githubusercontent.com/5694308/81145050-a809ad80-8f9f-11ea-943f-e865a6bedcda.png)

This is the same design as the temporary dashboard page, with the buttons leading to different pages 

## Content 
Title: Let's crunch the numbers...
Button 1: Blue Delta Stats (Leads to #150 Blue Delta Stats Page )
Button 2: Memo Stats (Leads to Memo Stats)

**Comment by chris-saburo** [comment]
I did implement second requirement.
Now I am going to implement first requirement which is about Top Nav.

**Comment by chris-saburo** [comment]
I have reverted it.

**Comment by paulchrisluke** [comment]
@chris-saburo the `stats` button in our bottom nav should link to this page please

**Comment by chris-saburo** [comment]
> @chris-saburo the `stats` button in our bottom nav should link to this page please

which page should be indicated clicking Stats button in Bottom Nav?
