### ISSUE TITLE
Edit Blue Delta Email

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/Volkswagen-email-corporate-communications-CMS#179]
# Design File
The specs for page can be found in the [Figma design file](https://www.figma.com/file/GONpIBrQ53ukjJhq0Hl9su/Volkswagen-New?node-id=1713%3A22637)

For the design and the flow, go to the "Prototype" page. This issue is for the blue delta stats page/open rate page  

# Edit Blue Delta Email
![image](https://user-images.githubusercontent.com/5694308/81145861-62e67b00-8fa1-11ea-9c3b-0a9047316512.png)
In this page, you can edit the recipients and the send time of the day's email. To rearrange, simply tap on the preview overlay where it says "rearrange" 

It uses our pre-built top navigation, distribution list addition component, text field, and button styling as we do in other pages. 

# Top Navigation 
![image](https://user-images.githubusercontent.com/5694308/81146130-e2744a00-8fa1-11ea-9e65-870dbe42d3f6.png)

## Content 
This is the same as all the top navigations (/src/components/BaseAppBarHeader.vue)
Title: {{ Date of Blue Delta Email selected }}  
Back Icon: (Leads to Blue Delta Page #174 )

# Rearrange Overlay 
![image](https://user-images.githubusercontent.com/5694308/81145997-a7721680-8fa1-11ea-919a-9b11ef4cc8c7.png)
this is a preview overlay with "rearrange" text. You can click anywhere in the preview to start the rearrangment process 

## Text Style 
Text Button: 
/* Mobile Color Label */

font-family: Work Sans;
font-style: normal;
font-weight: 500;
font-size: 14px;
line-height: 24px;
/* identical to box height, or 171% */

letter-spacing: 0.02em;
text-transform: uppercase;
```

## Color 
Text Button: On Primary, High Emphasis (#FFFFFF, 84%) 
Overlay: #000000, 60%

**Comment by paulchrisluke** [comment]
Reviewed according to https://deploy-preview-204--vw-email-cms.netlify.app/blue-delta/edit/37

# Drop Down 
![image](https://user-images.githubusercontent.com/5694308/81502833-96f7ce00-930a-11ea-888b-37e6a4109bcd.png)
Current drop down menu for recipients is above the text field. Drop down should be below to maintain consistency with the rest of our components 

# Expansion Panel 
![image](https://user-images.githubusercontent.com/5694308/81502872-e2aa7780-930a-11ea-83b7-7294d99ceb29.png)
Current expansion panel has label text in the middle of the component and no preview for selected option 

![image](https://user-images.githubusercontent.com/5694308/81502995-72502600-930b-11ea-82da-1095ae1c19d4.png)
The contents of the drop down menu is currently centered

![image](https://user-images.githubusercontent.com/5694308/81502912-14bbd980-930b-11ea-859c-bcedbe6dff35.png)
**Image from "Schedule Article" as example**
To maintain consistency with other components used, we want a left aligned title "Send Time" with a preview of a default displayed time that changes to selected time after drop down is selected. Drop down options are also left aligned instead of centered

**Comment by paulchrisluke** [comment]
# Expansion Panel 
![image](https://user-images.githubusercontent.com/5694308/81505107-3e7afd80-9317-11ea-90b8-e53e39bb7744.png)
This is what the expansion panel currently looks like 

![image](https://user-images.githubusercontent.com/5694308/81505054-f6f47180-9316-11ea-97c8-d2b1293211aa.png)
This is what the expansion panel should always look like. Only the preview of the saved time should change

## Color
Label: On Background, High emphasis 
Time Preview: On background, Medium Emphasis 

# Save Function
It seems like the the time is not actually saved for the jumpstart. When I set a time, click save, navigate away from the page, and come back, the preview still says "send time" without displaying the saved time in the preview 

# Rearrange Component 
"Rearrange" text on top of image should be html 
SVG of icon in zip file below
[Rearrange.zip](https://github.com/whynotearth/Volkswagen-email-corporate-communications-CMS/files/4606134/Rearrange.zip)

**Comment by paulchrisluke** [comment]
@ctyar can we make it so that if default settings are set in #187 that they appear by default here?

**Comment by ctyar** [comment]
@paulchrisluke This should be fixed now
