### ISSUE TITLE
update category selector

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/Volkswagen-email-corporate-communications-CMS#182]
remove the bottom stepper progression bar, its confusing. Instead, when someone taps/clicks a category, automatically progress to the next step. 

![gif](https://i.gyazo.com/bae212a602a48bd0fea7f56407f7e1e1.gif)
On tap, the selected category slides to the top and the associated form will appear to slide down from the displayed category

**Comment by paigefreeman271** [comment]
assigning @abdullahcalisir12 to help @chris-saburo

**Comment by abdullahcalisir12** [comment]
@chris-saburo I updated article categeory selection at #342 branch you can check and if you have any work you can merge this to your local branch and continue working without waiting to be merged to staging

**Comment by chris-saburo** [comment]
Yes, now I am checking it.
