### ISSUE TITLE
Blue Delta Settings Page

### ISSUE THREAD

**Issue by paigefreeman271** [whynotearth/Volkswagen-email-corporate-communications-CMS#187]
# Design File
The specs for page can be found in the [Figma design file](https://www.figma.com/file/GONpIBrQ53ukjJhq0Hl9su/Volkswagen-New?node-id=1960%3A61876)
In the Volkswagen prototype page 

# Blue Delta Settings
Your mission, should you accept, includes these tasks: 

- [x] 1. [Top Navigation ](#top-navigation)  
- [x] 2. [Text Input](#text-input) 
- [x] 3. [Expansion Panel](#expansion-panel)

![image](https://user-images.githubusercontent.com/63047208/81267980-81b44280-9071-11ea-84bc-575a5885a599.png)

<h1 id="top-navigation">1. Top Navigation</h1> 

![image](https://user-images.githubusercontent.com/63047208/81268314-fdae8a80-9071-11ea-8c89-8d508f7d08ec.png)

## Content 
Title: Blue Delta Settings
Back: Settings

## Text Style
Title: 
```
/* Mobile H2 */

font-family: Work Sans;
font-style: normal;
font-weight: 600;
font-size: 22px;
line-height: 26px;
/* identical to box height */
```

## Colors 
Top Nav Bar Background: Surface (#FFFFFF, 100%)
Title: On Primary (#011D51, 100%)

## Shadow 
Top Navigation Bar; 
```
/* 4 dp */

background: #C4C4C4;
box-shadow: 0px 1px 10px rgba(0, 0, 0, 0.2), 0px 4px 5px rgba(0, 0, 0, 0.12), 0px 2px 4px rgba(0, 0, 0, 0.14);
```

<h1 id="text-input">2. Text Input</h1> 

![image](https://user-images.githubusercontent.com/63047208/81268705-7b729600-9072-11ea-97c4-8405822d2a8a.png)

## Content 
Text Label: By default, Blue Delta will automatically send each day according to the below details. You can change these manually for each individual Blue Delta here.  #174 

Text Field Label: This will be a drop down, this issue was already created in the internal memo form 
See code here: 
https://github.com/whynotearth/Volkswagen-email-corporate-communications-CMS/blob/staging/src/views/MemoAdd.vue
https://github.com/whynotearth/Volkswagen-email-corporate-communications-CMS/blob/staging/src/components/BaseDropdown.vue
https://github.com/whynotearth/Volkswagen-email-corporate-communications-CMS/blob/staging/src/components/BaseChip.vue

Floating Text Label:  Default Distribution List

## Text Style
Text Label: 
```
/* Mobile Body 1 */

font-family: Work Sans;
font-style: normal;
font-weight: normal;
font-size: 16px;
line-height: 20px;
/* or 125% */

display: flex;
align-items: center;
```

Text Field Label: See internal writing memo form
Floating Text Label: 
```
/* Mobile Caption */

font-family: Work Sans;
font-style: normal;
font-weight: normal;
font-size: 12px;
line-height: 16px;
/* identical to box height, or 133% */

display: flex;
align-items: center;
```

## Color 
Text Label: On background, High Emphasis (#000000, 84%)
Hyperlink: Secondary color (03B3F9, 100%)
Text Field Label: see internal writing memo form
Floating Text Label: On background, medium emphais (#000000, 54%)

<h1 id="Expansion-Panel">3. Expansion Panel</h1> 

![image](https://user-images.githubusercontent.com/63047208/81271840-d4dcc400-9076-11ea-9bd1-0bae16cb51c1.png)

## Content
Please note: these have dividers and not shadows

Text Label: Time
**please see time drop down component which was already created in the post creation form
https://github.com/whynotearth/Volkswagen-email-corporate-communications-CMS/blob/staging/src/views/PostAdd.vue
See "Schedule Post" 

## Text Style

Text Label: 
```
/* Mobile Body 1 */

font-family: Work Sans;
font-style: normal;
font-weight: normal;
font-size: 16px;
line-height: 20px;
/* or 125% */

display: flex;
align-items: center;
```

## Color
Text Field: On background, high emphasis (000000, 84%)

**Comment by paulchrisluke** [comment]
# Button 
![image](https://user-images.githubusercontent.com/5694308/81463634-2b681080-91e5-11ea-801c-7463e1fa67e7.png)
We added a "save" button to our designs for this page 

## Content 
Button Text: Save

## Text Style
Button Text: 
```
/* Mobile Color Label */

font-family: Work Sans;
font-style: normal;
font-weight: 500;
font-size: 14px;
line-height: 24px;
/* identical to box height, or 171% */

letter-spacing: 0.02em;
text-transform: uppercase;
```

## Color 
Button Background (25 px radius): Secondary, #03B3F9  
Button Text: On Secondary (#FFFFFF, 84%) 

# Divider
![image](https://user-images.githubusercontent.com/5694308/81463686-93b6f200-91e5-11ea-8ecd-d55469c33575.png)
Add this divider as well, visuals look great otherwise 

# Functionalities 
@mort3za @atharva3010 Can you help implementing function/logic in this page?

**Comment by paulchrisluke** [comment]
Ui looks good visually 
@mort3za or @atharva3010 , can one of you take care of functionality for this issue

**Comment by mort3za** [comment]
@paulchrisluke @chris-saburo  still has issue

![image](https://user-images.githubusercontent.com/510242/81473395-608b5780-9213-11ea-8877-bf00d985d692.png)

that **here** link not working too.

**Comment by chris-saburo** [comment]
Done it.

**Comment by chris-saburo** [comment]
I done it.
