### ISSUE TITLE
Make article editing date selection component consistent in ui

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/Volkswagen-email-corporate-communications-CMS#209]
This is related to this issue: https://github.com/whynotearth/Volkswagen-email-corporate-communications-CMS/issues/170
and this PR: https://github.com/whynotearth/Volkswagen-email-corporate-communications-CMS/pull/184

UI is inconsistent with expansion panel designs in other time selection expansion panels of the site 

Current it is on 2 lines, where the title is placed above the preview and there are no color difference between title and preview 
![image](https://user-images.githubusercontent.com/5694308/81533310-2eebcb00-9390-11ea-842e-2423ffcf24c2.png)

## Fix 
![image](https://user-images.githubusercontent.com/5694308/81533654-c51ff100-9390-11ea-9af4-5768222f5a73.png)
We want to use the same expansion panel style we've been using, with a label and preview of selected date. 

### Color
Label: On Background, High Emphasis (#000000, 84%) 
Preview: On Background, medium emphasis (#000000, 54%) 

### Content 
Label: Schedule 
Preview: {{ display previously saved or default time }}

**Comment by bamboochow** [comment]
@chris-saburo please mention this issue in associated PR

**Comment by paulchrisluke** [comment]
@chris-saburo what is the PR for us to review here?
