### ISSUE TITLE
UI deosn't respect the the 401(Not authenticated) result from API

### ISSUE THREAD

**Issue by ctyar** [whynotearth/Volkswagen-email-corporate-communications-CMS#211]
If the API at any point returns 401 or 403 the UI should redirect the user to the login page.
Right now user can continue browsing the app while most things don't work.

![Untitled](https://user-images.githubusercontent.com/1432648/81542194-82a6e600-9389-11ea-8c4e-6cd190d7e583.png)

**Comment by mort3za** [comment]
Correct, this is for the API links that don't use axios, e.g. email preview. Will fix.

**Comment by smebrahimi** [comment]
@paulchrisluke This bug fix seems to require more testing

**Comment by mort3za** [comment]
@smebrahimi I guess this happens when backend deployed (cookies will expire after deploy).

**Comment by mort3za** [comment]
I saw that our preview image is now base64 so it won't be an issue anymore.
