### ISSUE TITLE
make blue delta auto sending optional

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/Volkswagen-email-corporate-communications-CMS#217]
# Design File
The specs for page can be found in the [Figma design file](https://www.figma.com/file/GONpIBrQ53ukjJhq0Hl9su/Volkswagen-New?node-id=1960%3A61876)
In the Volkswagen prototype page 

# Previous Design 
https://github.com/whynotearth/Volkswagen-email-corporate-communications-CMS/issues/187
Our previous Blue Delta Settings Page looks like this 
![image](https://user-images.githubusercontent.com/63047208/81267980-81b44280-9071-11ea-84bc-575a5885a599.png)

Related PRs: 
https://github.com/whynotearth/Volkswagen-email-corporate-communications-CMS/pull/195

# Updated Design
![image](https://user-images.githubusercontent.com/5694308/81551743-9283f180-93ac-11ea-986e-49b8eaa1c6c5.png)
We are adding a toggle to send email automatically. If selected, emails will be sent automatically each day. 

Else, it will have to be sent manually every day. The setting options will not be visible if the toggle is not on. 
![image](https://user-images.githubusercontent.com/5694308/81552970-9b75c280-93ae-11ea-91d8-b47610e04ef5.png)

## Content 
Text: Send Email Automatically 

## Text Style 
Text: 
```
/* Mobile Body 1 */

font-family: Work Sans;
font-style: normal;
font-weight: normal;
font-size: 16px;
line-height: 20px;
/* identical to box height, or 125% */
```

## Color 
Text: On Background, High Emphasis (#000000, 84%) 
Divider: On Background, Divider (#000000, 12%) 
![image](https://user-images.githubusercontent.com/5694308/81552348-8c424500-93ad-11ea-947b-e5dbbd5a52d9.png)
Toggle Off Knob: Surface (#FFFFFF) 
Toggle Off Track; On background, Disabled (#000000, 38%) 
![image](https://user-images.githubusercontent.com/5694308/81552487-c0b60100-93ad-11ea-9106-da47a3a783f1.png)
Toggle on Knob: Secondary (#03B3F9)
Toggle On Track: Secondary, Medium Emphasis (#03B3F9, 54%)

**Comment by smebrahimi** [comment]
@ctyar Please notify me when the backend is ready

**Comment by ctyar** [comment]
@smebrahimi Added the new setting here `/api/v0/volkswagen/settings`

**Comment by bamboochow** [comment]
# Distribution List Search 
![image](https://user-images.githubusercontent.com/14948326/82319690-3ea48880-99fc-11ea-8c66-3ab469bd06b5.png)
The distribution list search feature is not showing available list even when information matches 

# Toggle Issues 
Leaving the page and coming back shows that the toggle settings are not saved. 

![gif](https://i.gyazo.com/383e10718fbda228c3e18f77ce62cd39.gif)
If you set toggle as "off" and leave the page, toggle will automatically turn on when you come back to the "Blue Delta Settings" Page 

![gif](https://i.gyazo.com/2518332fbcb0e195a88c970eee89fe16.gif)
If you set toggle as "on", leave the page, and return to the "Blue Delta Settings" page, Toggle will be "off" but you'll see displayed content for "on" toggle

We want the toggle to maintain the same state as when we left the page.

**Comment by smebrahimi** [comment]
@bamboochow For saved data you must click on button, while you enter the page get data from backend then display correct value.
By default toggle is off after arrive data updated, I'll fix it.

**Comment by bamboochow** [comment]
@mort3za approved to merge, but there is ui issue, will write separate bug for it 
![gif](https://i.gyazo.com/3159bee1f38830b874497c20c2ad10a9.gif)
