### ISSUE TITLE
Add missing Bottom Navigation to non-input pages

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/Volkswagen-email-corporate-communications-CMS#240]
# Design File
The specs for page can be found in the [Figma design file](https://www.figma.com/file/GONpIBrQ53ukjJhq0Hl9su/Volkswagen-New?node-id=1713%3A22637)

For the design and the flow, go to the "Prototype (desktop)" page. This issue is for the blue delta page

# Add Bottom Navigation 
![image](https://user-images.githubusercontent.com/5694308/81653835-64131e80-945f-11ea-9b6b-a65cc6a939d5.png)
The articles page needs a bottom navigation identical to all other pages 
route: /article-lists
See code: 
https://github.com/whynotearth/Volkswagen-email-corporate-communications-CMS/blob/staging/src/views/ArticleLists.vue
https://github.com/whynotearth/Volkswagen-email-corporate-communications-CMS/blob/staging/src/components/BaseNavigationBottom.vue

**Comment by paulchrisluke** [comment]
@chris-saburo please also add #fff color to active routes on bottom nav. That color should ease in like material design 
![Screenshot_20200512-203006](https://user-images.githubusercontent.com/5694308/81700564-026ca780-9493-11ea-910a-be7667c728b3.png)

**Comment by chris-saburo** [comment]
Done it.
