### ISSUE TITLE
Update Draft Article Flow

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/Volkswagen-email-corporate-communications-CMS#242]
# Design File
The specs for page can be found in the [Figma design file](https://www.figma.com/file/GONpIBrQ53ukjJhq0Hl9su/Volkswagen-New?node-id=1713%3A22637)

For the design and the flow, go to the "Prototype (mobile)" page. This issue is for the Article drafting flow 

# Previous Designs 
![image](https://user-images.githubusercontent.com/5694308/81657480-1b109980-9462-11ea-970a-6b4b2677409a.png)
![image](https://user-images.githubusercontent.com/5694308/81657506-21067a80-9462-11ea-8d93-e473127e81a5.png)
![image](https://user-images.githubusercontent.com/5694308/81657864-73479b80-9462-11ea-9a69-d303b68d1bcd.png)
Previous designs included a 3 step stepper navigation:
1. select category 
2. create post 
3. preview  

# Update Draft Article Flow 
Your mission, should you choose to accept: 
Our new "draft article flow" will no longer have the stepper navigation. We are replacing the stepper nav with our top navigation and removing the preview. 
![image](https://user-images.githubusercontent.com/14948326/82799204-dfcf8b00-9ea3-11ea-8e9e-be73a0683790.png)

- [ ] Update "add article" form to include image captions
- [ ] Add "change category" feature
- [ ] Change stepper navigation to standard top navigation 
- [ ] Remove the 3rd step: Preview 

# Update "add/edit article" form 
The add article form and the edit article form needs to be rearranged, with a new "image caption" field added. 
The new order for the form is: 
1. Category Selection (change category) 
2. Headline
3. Image Upload
4. Excerpt 
5. Description 
6. Schedule Article
![image](https://user-images.githubusercontent.com/14948326/82799148-c595ad00-9ea3-11ea-8c42-f17e1cb60403.png)

The excerpt has a character cap of 175, and the description has a character cap of 450. However, if no image is uploaded, the 175 excerpt character cap can be added to the description, for a total of 625 characters in an article. 

The exerpt always becomes the 1st paragraph of the article.
![image](https://user-images.githubusercontent.com/14948326/82798971-7a7b9a00-9ea3-11ea-927e-f52fc44426ec.png)
![image](https://user-images.githubusercontent.com/14948326/82799093-aeef5600-9ea3-11ea-90e2-85767ee4434d.png)

https://github.com/whynotearth/Volkswagen-email-corporate-communications-CMS/blob/staging/src/views/ArticleListsItem.vue

# Change Category Feature
![image](https://user-images.githubusercontent.com/5694308/81658874-5f506980-9463-11ea-85f9-f86208169127.png)
We are adding the category component to the new article form 

![image](https://user-images.githubusercontent.com/5694308/81660986-accdd600-9465-11ea-9a1a-f50980a7d45a.png)
On tap, show drop down menu with category selectors to change categories. Once categories are changed, the form will change to the correct category form 

![image](https://user-images.githubusercontent.com/5694308/81660594-2913e980-9465-11ea-9182-cccf5f159d97.png)
The category selector component needs to be abstracted here: 
https://github.com/whynotearth/Volkswagen-email-corporate-communications-CMS/blob/staging/src/components/ArticleAddStep1.vue

# Change Top Navigation 
Our previous navigation was a stepper navigation. 

Our new navigation will be our standard top navigation. 
![image](https://user-images.githubusercontent.com/5694308/81661301-1c43c580-9466-11ea-8848-0aa1b90d2c2c.png)
![image](https://user-images.githubusercontent.com/5694308/81661317-2239a680-9466-11ea-8eeb-4309d8a06c5b.png)

## Behavior 
Starting at the "select category" page, once you tap to select a category the page immediately changes to the "add new article" form for the selected category. Selecting "back" from the "add new articles" page will still lead to "select category" page

# Remove Preview Step 
The preview step will no longer be part of the draft article flow 
![image](https://user-images.githubusercontent.com/5694308/81661942-11d5fb80-9467-11ea-93a4-e2f4cd8d53df.png)

# Related PRs 
Add articles: https://github.com/whynotearth/Volkswagen-email-corporate-communications-CMS/pull/132
UI of Add Articles step 1: https://github.com/whynotearth/Volkswagen-email-corporate-communications-CMS/pull/130
add navigation and post-add: https://github.com/whynotearth/Volkswagen-email-corporate-communications-CMS/pull/2/files
edit/delete articles: https://github.com/whynotearth/Volkswagen-email-corporate-communications-CMS/pull/184

**Comment by mort3za** [comment]
@abdullahcalisir12 please change `maxImageWidth: 160` to `maxImageWidth: 560` in ImageUpload.vue:14

**Comment by bamboochow** [comment]
@abdullahcalisir12 Please add new excerpt feature into add/edit post 
![image](https://user-images.githubusercontent.com/14948326/82812783-f256be00-9ebd-11ea-82a3-11d7e1b2a19e.png)
