### ISSUE TITLE
fixing position of article in rearrange

### ISSUE THREAD

**Issue by smebrahimi** [whynotearth/Volkswagen-email-corporate-communications-CMS#256]
https://share.vidyard.com/watch/SZcm1mKPzUhJWPA3reqxk2?

**Comment by smebrahimi** [comment]
It has this problem now
https://share.vidyard.com/watch/SZcm1mKPzUhJWPA3reqxk2?

**Comment by paulchrisluke** [comment]
@smebrahimi is this review for UX or code? if UX, what should we be checking?

**Comment by mort3za** [comment]
@paulchrisluke This needs a UX review. check the gif link please. The whole experience when you select and unselect articles in blue delta re-arrange.
