### ISSUE TITLE
Replace static name "Xavier" with "Hello Sunshine!"

### ISSUE THREAD

**Issue by atharva3010** [whynotearth/Volkswagen-email-corporate-communications-CMS#268]
On the dashboard, the name is hardcoded as "Xavier" right now. We need to show the name fetched from the profile endpoint. This means that:

- We need to call GET profile endpoint on dashboard load.
- We need to add it to profile.js module.

**Comment by atharva3010** [comment]
This issue should be worked on after #265 is merged.

**Comment by paulchrisluke** [comment]
I order to make this a bit less complex can we just place a static "Hello Sunshine!"
