### ISSUE TITLE
Dashboard "review and send" Reroute

### ISSUE THREAD

**Issue by bamboochow** [whynotearth/Volkswagen-email-corporate-communications-CMS#289]
# Design File
The specs for page can be found in the [Figma design file](https://www.figma.com/file/GONpIBrQ53ukjJhq0Hl9su/Volkswagen-New?node-id=1713%3A22637)

For the design and the flow, go to the "Prototype (mobile)" page. This issue is for the blue delta page

# Dashboard Button Reroute
Currently the Dashboard's "Review and Send" Button goes to "Blue Delta List" ( /jumpstart-lists ) page on thebluedelta.com and staging.thebluedelta.com
![gif](https://i.gyazo.com/d032b3b98d38b8897fd00ff15621dda3.gif)

We want the "Review and Send" button to always go to today's "Blue Delta Rearrange" page ( /blue-delta/edit/{Blue Delta ID} )
![gif](https://i.gyazo.com/5ac0e5186609ab4590e23b1cf28ff0b7.gif)

# Related PR / Issues / Code 
Blue Delta List: https://github.com/whynotearth/Volkswagen-email-corporate-communications-CMS/pull/213
Dashboard code: https://github.com/whynotearth/Volkswagen-email-corporate-communications-CMS/blob/0c64229e6baea7897d42143208bafbff1385bf51/src/views/Dashboard.vue
Edit Blue Delta Code: https://github.com/whynotearth/Volkswagen-email-corporate-communications-CMS/blob/7bb69d1601b72afbf2d3697f232dc099df2e9a74/src/views/EditBlueDelta.vue

**Comment by paulchrisluke** [comment]
@smebrahimi brought up a good point if there is no blue Delta scheduled for the day we should hide the button.
