### ISSUE TITLE
Remove price field from event article form

### ISSUE THREAD

**Issue by bamboochow** [whynotearth/Volkswagen-email-corporate-communications-CMS#290]
# Affected PR / Code / Issues 
Article Add Code: https://github.com/whynotearth/Volkswagen-email-corporate-communications-CMS/blob/7bb69d1601b72afbf2d3697f232dc099df2e9a74/src/views/ArticleAdd.vue
Article Add Step 2 Component Code: https://github.com/whynotearth/Volkswagen-email-corporate-communications-CMS/blob/7bb69d1601b72afbf2d3697f232dc099df2e9a74/src/components/ArticleAddStep2.vue
```
 price: {
      required: requiredIf(context => {
        return context.isFieldRequired('price');
      }),
```

# Previous 
Our previous designs has price included as a field in the event article form 
![image](https://user-images.githubusercontent.com/14948326/82631849-c36fec00-9c20-11ea-8008-558b076902c9.png)

# Updated Design
Our new design will not include the "price" field in the article form. Delete the "price" field from the code. 
![image](https://user-images.githubusercontent.com/14948326/82631896-e6020500-9c20-11ea-8b17-924d5be494cc.png)

# Design File
The specs for page can be found in the [Figma design file](https://www.figma.com/file/GONpIBrQ53ukjJhq0Hl9su/Volkswagen-New?node-id=1713%3A22637)

For the design and the flow, go to the "Prototype" page. This issue is for the blue delta stats page/open rate page

**Comment by smebrahimi** [comment]
@ctyar please remove price from backend

**Comment by ctyar** [comment]
Done
