### ISSUE TITLE
allow pressing enter to log in

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/Volkswagen-email-corporate-communications-CMS#307]
on login screen, you have to click login. pressing enter should submit our submit buttons

**Comment by paulchrisluke** [comment]
@smebrahimi can we allow pressing enter anywhere on the screen? In this preview you have to be selecting the field to press enter to log in

**Comment by mort3za** [comment]
> @smebrahimi can we allow pressing enter anywhere on the screen? In this preview you have to be selecting the field to press enter to log in

That's not a normal behavior and will cause problem for keyboard users who want to open links (e.g. forgot password link) @paulchrisluke

**Comment by IgorVieira** [comment]
> > @smebrahimi can we allow pressing enter anywhere on the screen? In this preview you have to be selecting the field to press enter to log in
> 
> That's not a normal behavior and will cause problem for keyboard users who want to open links (e.g. forgot password link) @paulchrisluke

Fixed I have changed the event for be able to triggered everywhere
