### ISSUE TITLE
When error occures in add blue-delta, user don't see anything

### ISSUE THREAD

**Issue by mort3za** [whynotearth/Volkswagen-email-corporate-communications-CMS#318]
We need to setup error handling in edit/add blue-delta

![image](https://user-images.githubusercontent.com/510242/82781162-58b3f000-9e6e-11ea-927a-a0f75c04475b.png)

Above error happend on this url: `/blue-delta/add/2020-05-26T09:00:00`  
Payload: `{"articleIds":[238],"dateTime":"2070-10-19T04:30:00.000Z","distributionGroups":["Dev Test"]}`  
Response: 400 {"message":"Not all of the articles of the day are selected"}  
Console error: _this.update_response_message is not a function (EditBlueDelta.vue:203)

**Comment by atharva3010** [comment]
Whoever is going to work on this, BlueDeltaRearrange has error handling there, you can use the same implementation in EditBlueDelta.
