### ISSUE TITLE
Articles Jump Page

### ISSUE THREAD

**Issue by bamboochow** [whynotearth/Volkswagen-email-corporate-communications-CMS#344]
# Design File
The specs for page can be found in the [Figma design file](https://www.figma.com/file/GONpIBrQ53ukjJhq0Hl9su/Volkswagen-New?node-id=1713%3A22637)

For the design and the flow, go to the "Prototype (mobile)" page. This issue is for the Article drafting flow 

# Similar PR / Code: 
Stats Page: https://github.com/whynotearth/Volkswagen-email-corporate-communications-CMS/blob/staging/src/views/Stats.vue

Top Navigation: https://github.com/whynotearth/Volkswagen-email-corporate-communications-CMS/blob/staging/src/components/BaseAppBarHeader.vue

Bottom Nav: https://github.com/whynotearth/Volkswagen-email-corporate-communications-CMS/blob/staging/src/components/BaseNavigationBottom.vue

# Article Jump Page 
Your mission, should you choose to accept: 
This is the jump page to transition between all article related pages. 

- [x] 1. [Top Navigation](#top-navigation)
- [x] 2. [Title](#title)
- [x] 3. [Buttons](#buttons)
- [x] 4. [Bottom Nav](#bottom-nav)

![image](https://user-images.githubusercontent.com/14948326/83222679-1870ac80-a1a3-11ea-81b1-90d9f0342f96.png)

<h1 id="top-navigation">1. Top Navigation</h1> 

This is an identical component to this one: https://github.com/whynotearth/Volkswagen-email-corporate-communications-CMS/blob/staging/src/components/BaseAppBarHeader.vue

### Content 
Title: Articles
Back Icon: (Leads to Dashboard)

<h1 id="title">2. Title</h1> 

The code for the title/logo is below: 
```
 <div class="max-w-sm mx-auto px-12">
            <div class="mb-4">
              <img
                class="w-24 h-24 mx-auto block"
                src="https://res.cloudinary.com/whynotearth/image/upload/v1588067012/Volkswagen/cms/Volkswagen_logo_2019_1_ddafyt.svg"
                alt=""
              />
            </div>
            <h1 class="text-primary h1-mobile md:h1 mb-h1-mobile">Time to make some content!</h1>
```

<h1 id="buttons">3. Buttons</h1> 
The buttons are identical to the ones on this page: 
https://github.com/whynotearth/Volkswagen-email-corporate-communications-CMS/blob/staging/src/views/Stats.vue

### Content
Button 1: Scheduled Articles ( Goes to the Articles Page `/article-lists`)
Button 2: New Article ( Goes to Article Writing `/articles/add/:step?`)

<h1 id="bottom-nav">4. Bottom Nav</h1> 
This is the IDENTICAL component (in every way. Just use this one.):  https://github.com/whynotearth/Volkswagen-email-corporate-communications-CMS/blob/staging/src/components/BaseNavigationBottom.vue

**Comment by chris-saburo** [comment]
Done it.
