### ISSUE TITLE
Text cuttoff after new typography style updates

### ISSUE THREAD

**Issue by mort3za** [whynotearth/Volkswagen-email-corporate-communications-CMS#375]
![image](https://user-images.githubusercontent.com/510242/83895749-5f910b80-a768-11ea-8e27-2da7a8d8cb4c.png)

Line-height 40px is not suitable for header.

.tg-h2-desktop {
    font-family: 'VWHead-Bold', sans-serif;
    font-style: normal;
    font-weight: bold;
    font-size: 44px;
    line-height: 40px;
  }

**Comment by paulchrisluke** [comment]
@mort3za do you need a new font size from us on this?

**Comment by mort3za** [comment]
No, Seems the problem is only line height, I can fix it myself.  
I guess line-height rendering is different in Figma.
