### ISSUE TITLE
Unable to submit Email Edits

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/Volkswagen-email-corporate-communications-CMS#53]
This bug is present on https://vw-email-cms.netlify.app/ and on various deploy previews, including https://deploy-preview-51--vw-email-cms.netlify.app/

# Unble to submit email edits 
![image](https://user-images.githubusercontent.com/5694308/80335662-2e770e80-887f-11ea-9259-3340564d183a.png)
![image](https://user-images.githubusercontent.com/5694308/80335222-d8ee3200-887d-11ea-811d-3651740ba59e.png)
I'm getting this error when I'm trying to edit an individual email in a list in the #48 Edit Email page

**Comment by mort3za** [comment]
@paulchrisluke I tried editing a new email address (also editing an existing email address) and it was fine. could you write the steps to reproduce this error?
