### ISSUE TITLE
Extra Text in Delivered Email Titles

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/Volkswagen-email-corporate-communications-CMS#56]
The title of this email has some extra text that was not added during the memo drafting flow 
![image0 (11)](https://user-images.githubusercontent.com/5694308/80343302-d4327980-888f-11ea-9041-74472c3acbb5.png)

This is displayed in gmail, but not every single time (previous test memo displayed below) 
![image0 (12)](https://user-images.githubusercontent.com/5694308/80343626-6d619000-8890-11ea-8bdf-cd6549a0c7c5.png)

**Comment by ctyar** [comment]
Fixed in SendGrid account
