### ISSUE TITLE
Update Dashboard color

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/Volkswagen-email-corporate-communications-CMS#84]
# Design File
The specs for page can be found in the [Figma design file](https://www.figma.com/file/GONpIBrQ53ukjJhq0Hl9su/Volkswagen-New?node-id=1713%3A22637)

For the design and the flow, go to the "Prototype" page. 

# Dashboard 
![image](https://user-images.githubusercontent.com/5694308/80453638-df9aa900-8952-11ea-98e2-219c33838293.png)

# Color: 
Background: Background (#FFFFFF) 
Icon, Text, Logo: Primary (#011D51)

**Comment by smebrahimi** [comment]
https://res.cloudinary.com/whynotearth/image/upload/v1587275972/Volkswagen/cms/wheel_2_rk5nr4.png
@paulchrisluke  icon's color should be the primary color

**Comment by paulchrisluke** [comment]
https://res.cloudinary.com/whynotearth/image/upload/v1588066712/Volkswagen/cms/wheel_eqhded.svg
@smebrahimi here's the wheel icon (SVG)
