### ISSUE TITLE
Update Settings Page

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/Volkswagen-email-corporate-communications-CMS#93]
![image](https://user-images.githubusercontent.com/5694308/80492425-31145980-898e-11ea-93b9-b8ba13610467.png)

Change settings page to include 2 selections: 
1. Distribution Groups : leads to "Distribution Groups" https://github.com/whynotearth/Volkswagen-email-corporate-communications-CMS/issues/87
2. Log out

**Comment by mort3za** [comment]
It looks like there is a shadow below "log in"
That should be a 1 pixel divider in the color "On Background, Divider (#000000, 12%)

https://github.com/whynotearth/Volkswagen-email-corperate-communications/issues/40#issuecomment-617128653
