### ISSUE TITLE
Fix "import new group" Button to be within Margin

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/Volkswagen-email-corporate-communications-CMS#95]
![unknown](https://user-images.githubusercontent.com/5694308/80505361-6de84c80-899e-11ea-9768-72b91a5a687a.png)

Desktop for "Distribution Group" page has long button that needs to be within margin 
https://staging.thebluedelta.com/settings/email-lists

**Comment by linuxuser07** [comment]
was this fixed? I don't see it on firefox or chrome.

**Comment by mort3za** [comment]
Yes fixed
